### ISSUE TITLE
Arrange Data in Descending order

### ISSUE THREAD

**Issue by aniket0608** [Trident09/gcp-progress#5]
Want to see the data in descending order 
the on who completed 4 course and 4 quest and 1 gen ai should be in top and the who have not redeemed the sbuscriptiob should be at last..and the who redeem and working based on their progress they should be arranged.

**Comment by Trident09** [comment]
web dev lead ko karne bolo

**Comment by Trident09** [comment]
Feature added with a very small bug some students who have completed 4 course and 4 skills are displayed below students having 0 skills and 0 courses

**Comment by Trident09** [comment]
Feature added with a very small bug some students who have completed 4 course and 4 skills are displayed below students having 0 skills and 0 courses

**Comment by aniket0608** [comment]
great work
